### ISSUE TITLE
Import of the remark-gfm, rehype-slug and next-mdx-remote/serialize produce an error

### ISSUE THREAD

**Issue by mavr1k** [ricokahler/next-plugin-preval#94]
I'm working on processing MD and MDX content using remark-gfm, rehype-slug and next-mdx-remote/serialize but I'm receiving an error shown below. Any variation of import (import from, dynamic import and require) doesn't change the behavior. 

```
[next-plugin-preval] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/node_modules/remark-gfm/index.js from /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts not supported.
Instead change the require of index.js in /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.newLoader [as .js] (/Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/node_modules/pirates/lib/index.js:141:7)
    at /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts:2:75
    at async serializeContentTest (/Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts:2:18)
    at async Promise.all (index 0)
    at async getPartials (/Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts:4:461)
    at async getPartialsConfigs (/Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts:5:240)
    at async /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/node_modules/next-plugin-preval/dist/loader.js:106:14
    at async _prevalLoader (/Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/node_modules/next-plugin-preval/dist/loader.js:98:16)
error - ./src/preval/partials.preval.ts
Error: Failed to pre-evaluate "/Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts". Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/node_modules/remark-gfm/index.js from /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts not supported.
Instead change the require of index.js in /Users/Dmytro_Mavrosaus/projects/web-eos-documentation-client/src/preval/partials.preval.ts to a dynamic import() which is available in all CommonJS modules. See above for full stack trace.
```

**Comment by 1OGAG** [comment]
I have the same issue when using next-mdx-remote and serialize.

**Comment by getellez** [comment]
same problem here
